#!/usr/bin/env python3
"""
import_song.py - pull {note, divider} score arrays out of a sketch and
check them before they go anywhere near the hardware.

The jukebox uses the same flat array format as the single-buzzer original,
so importing a score is mostly a matter of moving it. The part worth
automating is the checking:

  * how many bars each voice actually contains,
  * whether the voices of a multi-voice arrangement agree in length
    (they must, or the buzzers will slide apart),
  * where the first bar line falls that does not add up,
  * how long the result plays at a given tempo.

Examples
--------
Inspect every array in a file:

    python3 tools/import_song.py original/chiptune_asrun.ino

Check a three-voice arrangement and report bar-by-bar alignment:

    python3 tools/import_song.py my679.txt --voices fettyLead,fettyArp,fettyBass --bpm 190

Emit a header ready to #include:

    python3 tools/import_song.py my679.txt --emit sketch/songs_user.h \\
        --voices fettyLead,fettyArp,fettyBass
"""

import argparse
import os
import re
import sys
from fractions import Fraction

# Accepts the shapes these arrays turn up in:
#   int x[] = {...};
#   const int x[] = {...};
#   const int x[] PROGMEM = {...};          <- AVR idiom, common in sketches
#   static const int x[] __attribute__((...)) = {...};
# The attribute slot between ] and = is what an earlier version missed,
# which made a PROGMEM sketch look like it contained no scores at all.
ARRAY_RE = re.compile(
    r"(?:static\s+)?(?:const\s+)?int\s+(\w+)\s*\[\s*\]"
    r"(?:\s*(?:PROGMEM|__attribute__\s*\(\(.*?\)\)))*"
    r"\s*=\s*\{(.*?)\}\s*;", re.S)
TOKEN_RE = re.compile(r"[A-Za-z_]\w*|-?\d+")


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    text = re.sub(r"//[^\n]*", " ", text)
    return text


def parse_arrays(text):
    """-> {name: [(note, divider), ...]}"""
    out = {}
    for m in ARRAY_RE.finditer(strip_comments(text)):
        name, body = m.group(1), m.group(2)
        toks = TOKEN_RE.findall(body)
        if len(toks) % 2:
            print(f"  ! {name}: {len(toks)} tokens - not an even "
                  f"note/duration count; last entry ignored", file=sys.stderr)
            toks = toks[:-1]
        pairs = []
        for i in range(0, len(toks), 2):
            try:
                div = int(toks[i + 1])
            except ValueError:
                print(f"  ! {name}: pair {i//2} has a non-numeric duration "
                      f"{toks[i+1]!r}", file=sys.stderr)
                continue
            pairs.append((toks[i], div))
        out[name] = pairs
    return out


def dur(divider):
    if divider == 0:
        return Fraction(0)
    if divider > 0:
        return Fraction(1, divider)
    return Fraction(3, 2) * Fraction(1, -divider)


def total(pairs):
    return sum(dur(d) for _, d in pairs)


def bar_report(pairs, name):
    """Walk the score and report every bar line that does not land cleanly."""
    pos = Fraction(0)
    bad = []
    for i, (n, d) in enumerate(pairs):
        start = pos
        pos += dur(d)
        # a note that straddles a bar line without ending on one
        if start < int(start) + 1 <= pos and pos != int(pos) and dur(d) < 1:
            bad.append((i, n, d, float(start), float(pos)))
    if bad:
        print(f"    note: {len(bad)} tie(s) cross a bar line in {name} (syncopation, "
              f"not an error); first at #{bad[0][0]} {bad[0][1]},{bad[0][2]} spans "
              f"bar {bad[0][3]:.3f}->{bad[0][4]:.3f}")
    return bad


def emit_array(name, pairs, per_row=8):
    lines = [f"const int {name}[] = {{"]
    row = []
    for n, d in pairs:
        row.append(f"{n},{d}")
        if len(row) == per_row:
            lines.append("  " + " ".join(f"{t}," for t in row))
            row = []
    if row:
        lines.append("  " + " ".join(f"{t}," for t in row))
    lines[-1] = lines[-1].rstrip(",")
    lines.append("};")
    return "\n".join(lines)



USER_HEADER = """/************************************************************
  songs_user.h - your own tracks
  GENERATED by tools/import_song.py. Regenerate, or edit by hand.

  Holds any number of three-voice tracks. Each one adds a row to
  USER_SONG_ENTRIES, which sketch.ino splices into its playlist.

  To add one:
      python3 tools/import_song.py <file> \\
          --voices <lead>,<harmony>,<bass> \\
          --bpm <n> --title "<name>" --install

  Installing a title that is already here replaces just that track and
  leaves the others alone.

  Tracks:
{summary}
************************************************************/

#ifndef SONGS_USER_H
#define SONGS_USER_H

#include "notes.h"

#define HAVE_USER_SONGS {count}

#if HAVE_USER_SONGS

"""


ENTRY_RE = re.compile(
    r'\{\s*"([^"]*)"\s*,\s*"([^"]*)"\s*,\s*(\d+)\s*,\s*\{\s*'
    r'SCORE\((\w+)\)\s*,\s*SCORE\((\w+)\)\s*,\s*SCORE\((\w+)\)')


def read_installed(path):
    """Existing tracks in songs_user.h -> [(title, style, bpm, [l,h,b])]."""
    if not os.path.exists(path):
        return []
    text = open(path).read()
    if re.search(r"#define\s+HAVE_USER_SONGS\s+0", text):
        return []
    arrays = parse_arrays(text)
    out = []
    for title, style, bpm, l, h, b in ENTRY_RE.findall(strip_comments(text)):
        if l not in arrays:
            continue
        out.append((title, style, int(bpm),
                    [arrays.get(l), arrays.get(h), arrays.get(b)]))
    return out


def install(arrays, names, args, source):
    """Add (or replace) a track in sketch/songs_user.h."""
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(here, "sketch", "songs_user.h")

    labels = ["lead", "harmony", "bass"]
    lens = [total(arrays[n]) for n in names]

    if len(set(lens)) != 1 and not args.force:
        print("\nrefusing to install: the voices do not agree in length.",
              file=sys.stderr)
        print("fix the score, or pass --force to install anyway.",
              file=sys.stderr)
        return 1

    voices = [arrays[n] for n in names]
    while len(voices) < 3:
        voices.append([("REST", 1)])

    tracks = read_installed(out)
    replaced = False
    for i, t in enumerate(tracks):
        if t[0] == args.title:
            tracks[i] = (args.title, args.style, args.bpm, voices)
            replaced = True
            break
    if not replaced:
        tracks.append((args.title, args.style, args.bpm, voices))

    # --- render ---
    summary, entries, blocks = [], [], []
    for i, (title, style, bpm, vs) in enumerate(tracks):
        bars = float(total(vs[0]))
        one_pass = bars * 4 * 60.0 / bpm
        passes = max(1, round(60.0 / one_pass)) if one_pass else 1
        summary.append(f"    {i + 1}. {title} ({style}), {bpm} BPM - "
                       f"{bars:g} bars, {one_pass:.1f} s x{passes} = "
                       f"{one_pass * passes:.1f} s")
        slots = [f"user{i}Lead", f"user{i}Harm", f"user{i}Bass"]
        # One physical line per entry: every line break inside a macro
        # needs its own continuation backslash, and a wrapped row here
        # silently truncated the macro.
        entries.append(f'  {{ "{title}", "{style}", {bpm}, '
                       f'{{ SCORE({slots[0]}), SCORE({slots[1]}), '
                       f'SCORE({slots[2]}) }} }},')
        blocks.append(f"// ---- {i + 1}. {title} ----")
        for k in range(3):
            blocks.append(f"// {labels[k]}")
            blocks.append(emit_array(slots[k], vs[k]))
        blocks.append("")

    body = [USER_HEADER.format(summary="\n".join(summary), count=len(tracks))]
    body.extend(blocks)
    body.append("// Spliced into PLAYLIST by sketch.ino. The trailing comma")
    body.append("// on the last row is deliberate.")
    body.append("#define USER_SONG_ENTRIES \\")
    body.append(" \\\n".join(entries).rstrip(",") + ",")
    body.append("")
    body.append("#endif  // HAVE_USER_SONGS\n")
    body.append("#endif  // SONGS_USER_H")

    with open(out, "w") as f:
        f.write("\n".join(body) + "\n")

    bars = float(lens[0])
    one_pass = bars * 4 * 60.0 / args.bpm
    passes = max(1, round(60.0 / one_pass)) if one_pass else 1
    verb = "replaced" if replaced else "added"
    print(f"\n{verb} \"{args.title}\" -> {out}")
    print(f"  {bars:g} bars at {args.bpm} BPM = {one_pass:.1f} s per pass, "
          f"x{passes} = {one_pass * passes:.1f} s")
    print(f"  {len(tracks)} user track(s) now installed:")
    for line in summary:
        print(line)
    print("\nnext:")
    print("  cd tools && make preview     # renders them to ../preview/*.wav")
    print("  cd tools && make verify      # checks their timing")
    return 0

def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("source", help=".ino / .h / .txt file containing the arrays")
    ap.add_argument("--voices", help="comma-separated lead,harmony,bass array "
                                     "names to cross-check")
    ap.add_argument("--bpm", type=int, default=120, help="tempo for the "
                                                         "duration estimate")
    ap.add_argument("--emit", metavar="HEADER", help="write the arrays to a header")
    ap.add_argument("--guard", default=None, help="include guard for --emit")
    ap.add_argument("--install", action="store_true",
                    help="write sketch/songs_user.h and enable the track")
    ap.add_argument("--title", default="My Track", help="track title for --install")
    ap.add_argument("--style", default="User", help="style label for --install")
    ap.add_argument("--force", action="store_true",
                    help="install even if the voices disagree in length")
    args = ap.parse_args()

    if args.install and not args.voices:
        # Fall back to file order: first three arrays are lead, harmony, bass.
        pass

    with open(args.source) as f:
        arrays = parse_arrays(f.read())

    if not arrays:
        print("no score arrays found", file=sys.stderr)
        return 1

    print(f"{os.path.basename(args.source)}: {len(arrays)} array(s), "
          f"durations quoted at {args.bpm} BPM\n")
    print(f"{'array':<22}{'notes':>7}{'bars':>9}{'seconds':>10}")
    print("-" * 48)
    for name, pairs in arrays.items():
        t = total(pairs)
        secs = float(t) * 4 * 60.0 / args.bpm
        bars = f"{float(t):.3f}".rstrip("0").rstrip(".")
        print(f"{name:<22}{len(pairs):>7}{bars:>9}{secs:>10.1f}")

    for name, pairs in arrays.items():
        bar_report(pairs, name)

    if args.voices:
        names = [v.strip() for v in args.voices.split(",")]
        missing = [n for n in names if n not in arrays]
        if missing:
            print(f"\nnot found in {args.source}: {', '.join(missing)}",
                  file=sys.stderr)
            return 1
        print("\nvoice alignment")
        print("-" * 48)
        lens = {n: total(arrays[n]) for n in names}
        lead = lens[names[0]]
        ok = True
        for n in names:
            delta = lens[n] - lead
            flag = "ok" if delta == 0 else f"OFF BY {float(delta):+.4f} bars"
            if delta != 0:
                ok = False
            print(f"  {n:<20}{float(lens[n]):>9.3f} bars   {flag}")
        if ok:
            secs = float(lead) * 4 * 60.0 / args.bpm
            loops = max(1, round(60.0 / secs)) if secs else 1
            print(f"\n  all voices agree: {float(lead):.0f} bars, "
                  f"{secs:.1f} s per pass, "
                  f"{loops} pass(es) = {secs*loops:.1f} s at {args.bpm} BPM")
        else:
            print("\n  voices disagree - the buzzers will slide apart. "
                  "Fix before importing.")
            return 1

    if args.emit:
        guard = args.guard or (os.path.basename(args.emit)
                               .upper().replace(".", "_").replace("-", "_"))
        body = [f"""/************************************************************
  {os.path.basename(args.emit)} - imported score data
  Generated by tools/import_song.py from {os.path.basename(args.source)}

  Flat {{note, divider}} arrays:
    divider  1 = whole, 2 = half, 4 = quarter, 8 = eighth,
            16 = sixteenth, negative = dotted (1.5x).
************************************************************/

#ifndef {guard}
#define {guard}

#include "notes.h"
"""]
        for name, pairs in arrays.items():
            t = total(pairs)
            body.append(f"\n// {name}: {len(pairs)} notes, "
                        f"{float(t):.0f} bars")
            body.append(emit_array(name, pairs))
        body.append(f"\n#endif  // {guard}")
        with open(args.emit, "w") as f:
            f.write("\n".join(body) + "\n")
        print(f"\nwrote {args.emit}")

    if args.install:
        if args.voices:
            names = [v.strip() for v in args.voices.split(",")]
        else:
            names = list(arrays)[:3]
            print(f"\nno --voices given; taking the first three arrays in "
                  f"file order as lead/harmony/bass: {', '.join(names)}")
        missing = [n for n in names if n not in arrays]
        if missing:
            print(f"not found in {args.source}: {', '.join(missing)}",
                  file=sys.stderr)
            return 1
        return install(arrays, names, args, args.source)

    return 0


if __name__ == "__main__":
    sys.exit(main())
