/************************************************************
  songs_classic.h - imported score data
  Generated by tools/import_song.py from chiptune_asrun.ino

  Flat {note, divider} arrays:
    divider  1 = whole, 2 = half, 4 = quarter, 8 = eighth,
            16 = sixteenth, negative = dotted (1.5x).
************************************************************/

#ifndef SONGS_CLASSIC_H
#define SONGS_CLASSIC_H

#include "notes.h"


// pokemonBattle: 410 notes, 129 bars
const int pokemonBattle[] = {
  A5,16, GS5,16, G5,16, FS5,16, A5,16, F5,16, FS5,16, F5,16,
  A5,16, E5,16, F5,16, E5,16, A5,16, DS5,16, E5,16, DS5,16,
  A5,16, D5,16, DS5,16, D5,16, A5,16, CS5,16, D5,16, CS5,16,
  A5,16, C5,16, CS5,16, C5,16, A5,16, B4,16, C5,16, B4,16,
  B5,8, REST,8, REST,4, REST,2, REST,1, B5,8, REST,8, REST,4,
  REST,2, REST,2, REST,4, A5,8, REST,8, B4,8, REST,4, CS5,8,
  REST,4, D5,8, REST,8, B4,8, CS5,8, REST,8, D5,8, REST,4,
  A5,8, AS5,8, B5,8, REST,4, CS6,8, REST,4, D6,8, REST,8,
  B5,8, CS6,8, REST,8, D6,8, REST,4, A5,8, REST,8, B4,4,
  B4,8, FS4,2, REST,8, REST,4, B4,4, FS4,4, B4,4, C5,1,
  REST,1, B4,4, B4,8, FS4,2, REST,8, REST,4, B4,4, FS4,4,
  B4,4, A4,1, REST,1, G4,1, D5,2, G4,2, A4,1, REST,1,
  G4,1, E5,2, FS5,2, E5,1, G5,4, A5,8, G5,8, FS5,8,
  E5,8, D5,8, E5,8, FS5,1, FS5,1, G5,1, G5,4, A5,8,
  G5,8, G5,8, FS5,8, E5,8, FS5,8, GS5,1, GS5,1, A5,1,
  CS6,2, E6,2, D6,4, A5,4, C6,8, B5,8, B5,1, B5,4,
  B5,2, D6,4, A5,4, AS5,8, F6,8, F6,2, F6,4, G6,1,
  E6,1, E6,2, E6,4, E6,8, B4,8, C5,4, C5,8, A4,8,
  A4,2, REST,4, C5,4, A4,4, C5,4, AS4,4, AS4,8, F5,2,
  REST,4, REST,8, AS4,4, F5,4, D5,4, C5,4, C5,8, A4,8,
  A4,2, REST,4, A4,4, E5,8, D5,8, C5,8, E5,8, D5,8,
  AS4,4, F5,8, F5,2, G5,4, G5,8, F5,4, F5,8, D5,4,
  F5,1, E5,1, D5,1, E5,1, F6,1, E6,1, G6,1, F6,1,
  E5,8, REST,4, E5,8, REST,4, E5,8, REST,8, E5,8, REST,4,
  E5,8, REST,4, E5,8, REST,8, E5,8, REST,4, E5,8, REST,4,
  E5,8, REST,8, E5,8, REST,4, E5,8, REST,4, E5,8, REST,8,
  A4,4, B4,4, G4,8, A4,8, A4,2, B4,8, CS5,8, E5,8,
  D5,8, CS5,8, B4,8, AS4,1, REST,8, AS4,8, C5,8, F5,8,
  E5,8, D5,8, C5,8, AS4,8, B4,1, REST,8, B4,8, CS5,8,
  G5,8, FS5,8, E5,8, D5,8, B4,8, C5,1, E5,2, G5,2,
  B4,4, B4,8, FS4,2, REST,8, REST,4, B4,4, FS4,4, B4,4,
  C5,1, REST,1, B4,4, B4,8, FS4,2, REST,8, REST,4, B4,4,
  FS4,4, B4,4, A4,1, REST,1, G4,1, D5,2, G4,2, A4,1,
  REST,1, G4,1, E5,2, FS5,2, E5,1, G5,4, A5,8, G5,8,
  FS5,8, E5,8, D5,8, E5,8, FS5,1, FS5,1, G5,1, G5,4,
  A5,8, G5,8, G5,8, FS5,8, E5,8, FS5,8, GS5,1, GS5,1,
  A5,1, CS6,2, E6,2, D6,4, A5,4, C6,8, B5,8, B5,1,
  B5,4, B5,2, D6,4, A5,4, AS5,8, F6,8, F6,2, F6,4,
  G6,1, E6,1, E6,2, E6,4, E6,8, B4,8, C5,4, C5,8,
  A4,8, A4,2, REST,4, C5,4, A4,4, C5,4, AS4,4, AS4,8,
  F5,2, REST,4, REST,8, AS4,4, F5,4, D5,4, C5,4, C5,8,
  A4,8, A4,2, REST,4, A4,4, E5,8, D5,8, C5,8, E5,8,
  D5,8, AS4,4, F5,8, F5,2, G5,4, G5,8, F5,4, F5,8,
  D5,4, F5,1, E5,1, D5,1, E5,1, F6,1, E6,1, G6,1,
  F6,1, E5,8, REST,4, E5,8, REST,4, E5,8, REST,8, E5,8,
  REST,4, E5,8, REST,4, E5,8, REST,8, E5,8, REST,4, E5,8,
  REST,4, E5,8, REST,8, E5,8, REST,4, E5,8, REST,4, E5,8,
  REST,8, A4,4, B4,4, G4,8, A4,8, A4,2, B4,8, CS5,8,
  E5,8, D5,8, CS5,8, B4,8, AS4,1, REST,8, AS4,8, C5,8,
  F5,8, E5,8, D5,8, C5,8, AS4,8, B4,1, REST,8, B4,8,
  CS5,8, G5,8, FS5,8, E5,8, D5,8, B4,8, C5,1, E5,2,
  G5,2, D5,1
};

// attackOnTitan: 68 notes, 10 bars
const int attackOnTitan[] = {
  D5,8, D5,8, F5,8, E5,4, C5,8, C5,8, D5,4, D5,8,
  F5,8, E5,4, C5,4, REST,8, A5,4, F5,8, G5,8, REST,8,
  E5,8, REST,8, F5,8, REST,8, D5,8, REST,8, E5,8, REST,8,
  C5,4, REST,8, A5,4, F5,8, G5,8, REST,8, E5,8, REST,8,
  F5,8, REST,8, E5,8, REST,8, D5,8, REST,8, C5,4, REST,8,
  C6,4, GS5,8, AS5,8, REST,8, G5,8, REST,8, GS5,8, REST,8,
  F5,8, REST,8, G5,8, REST,8, DS5,4, REST,8, C6,4, GS5,8,
  AS5,8, REST,8, G5,8, REST,8, GS5,8, REST,8, G5,8, REST,8,
  F5,8, REST,8, DS5,4, REST,8
};

// fullmetalAlchemist: 23 notes, 4 bars
const int fullmetalAlchemist[] = {
  E5,8, B5,4, E5,8, E5,4, D5,4, E5,8, B5,8, E5,8,
  E5,8, D5,16, E5,16, E5,8, FS5,4, FS5,16, FS5,16, FS5,8,
  G5,8, FS5,8, G5,8, FS5,8, B4,8, B4,4, REST,1
};

// superMario: 516 notes, 77 bars
const int superMario[] = {
  E5,8, E5,8, REST,8, E5,8, REST,8, C5,8, E5,8, REST,8,
  G5,8, REST,8, REST,4, G4,8, REST,4, REST,8, C5,8, REST,4,
  G4,8, REST,4, E4,8, REST,4, A4,8, REST,8, B4,8, REST,8,
  AS4,8, A4,8, REST,8, G4,8, E5,8, REST,8, G5,8, A5,8,
  REST,8, F5,8, G5,8, REST,8, E5,8, REST,8, C5,8, D5,8,
  B4,8, REST,4, C5,8, REST,4, G4,8, REST,4, E4,8, REST,4,
  A4,8, REST,8, B4,8, REST,8, AS4,8, A4,8, REST,8, G4,8,
  E5,8, REST,8, G5,8, A5,8, REST,8, F5,8, G5,8, REST,8,
  E5,8, REST,8, C5,8, D5,8, B4,8, REST,4, REST,4, G5,8,
  FS5,8, F5,8, DS5,8, REST,8, E5,8, REST,8, GS4,8, A4,8,
  C5,8, C5,8, A4,8, C5,8, D5,8, REST,4, G5,8, FS5,8,
  F5,8, DS5,8, REST,8, E5,8, REST,8, C6,8, REST,8, C6,8,
  C6,8, REST,8, REST,2, G5,8, FS5,8, F5,8, DS5,8, REST,8,
  E5,8, REST,8, GS4,8, A4,8, C5,8, C5,8, A4,8, C5,8,
  D5,8, REST,4, DS5,8, REST,4, D5,8, REST,4, C5,8, REST,4,
  REST,8, REST,2, REST,4, G5,8, FS5,8, F5,8, DS5,8, REST,8,
  E5,8, REST,8, GS4,8, A4,8, C5,8, C5,8, A4,8, C5,8,
  D5,8, REST,4, G5,8, FS5,8, F5,8, DS5,8, REST,8, E5,8,
  REST,8, C6,8, REST,8, C6,8, C6,8, REST,8, REST,2, G5,8,
  FS5,8, F5,8, DS5,8, REST,8, E5,8, REST,8, GS4,8, A4,8,
  C5,8, C5,8, A4,8, C5,8, D5,8, REST,4, DS5,8, REST,4,
  D5,8, REST,4, C5,8, REST,4, REST,8, REST,2, C5,8, C5,8,
  REST,8, C5,8, REST,8, C5,8, D5,8, REST,8, E5,8, C5,8,
  REST,8, A4,8, G4,8, REST,8, REST,4, C5,8, C5,8, REST,8,
  C5,8, REST,8, C5,8, D5,8, E5,8, REST,2, REST,2, C5,8,
  C5,8, REST,8, C5,8, REST,8, C5,8, D5,8, REST,8, E5,8,
  C5,8, REST,8, A4,8, G4,8, REST,8, REST,4, E5,8, E5,8,
  REST,8, E5,8, REST,8, C5,8, E5,8, REST,8, G5,8, REST,8,
  REST,4, G4,8, REST,8, REST,4, C5,8, REST,4, G4,8, REST,4,
  E4,8, REST,4, A4,8, REST,8, B4,8, REST,8, AS4,8, A4,8,
  REST,8, G4,8, E5,8, REST,8, G5,8, A5,8, REST,8, F5,8,
  G5,8, REST,8, E5,8, REST,8, C5,8, D5,8, B4,8, REST,4,
  C5,8, REST,4, G4,8, REST,4, E4,8, REST,4, A4,8, REST,8,
  B4,8, REST,8, AS4,8, A4,8, REST,8, G4,8, E5,8, REST,8,
  G5,8, A5,8, REST,8, F5,8, G5,8, REST,8, E5,8, REST,8,
  C5,8, D5,8, B4,8, REST,4, E5,8, C5,8, REST,8, G4,8,
  REST,4, GS4,8, REST,8, A4,8, F5,8, REST,8, F5,8, A4,8,
  REST,8, REST,4, B4,8, A5,8, REST,8, A5,8, A5,8, G5,8,
  REST,8, F5,8, E5,8, C5,8, REST,8, A4,8, G4,8, REST,8,
  REST,4, E5,8, C5,8, REST,8, G4,8, REST,4, GS4,8, REST,8,
  A4,8, F5,8, REST,8, F5,8, A4,8, REST,8, REST,4, B4,8,
  F5,8, REST,8, F5,8, F5,8, E5,8, REST,8, D5,8, C5,8,
  REST,8, REST,4, REST,2, E5,8, C5,8, REST,8, G4,8, REST,4,
  GS4,8, REST,8, A4,8, F5,8, REST,8, F5,8, A4,8, REST,8,
  REST,4, B4,8, A5,8, REST,8, A5,8, A5,8, G5,8, REST,8,
  F5,8, E5,8, C5,8, REST,8, A4,8, G4,8, REST,8, REST,4,
  E5,8, C5,8, REST,8, G4,8, REST,4, GS4,8, REST,8, A4,8,
  F5,8, REST,8, F5,8, A4,8, REST,8, REST,4, B4,8, F5,8,
  REST,8, F5,8, F5,8, E5,8, REST,8, D5,8, C5,8, REST,8,
  REST,4, REST,2, C5,8, C5,8, REST,8, C5,8, REST,8, C5,8,
  D5,8, REST,8, E5,8, C5,8, REST,8, A4,8, G4,8, REST,8,
  REST,4, C5,8, C5,8, REST,8, C5,8, REST,8, C5,8, D5,8,
  E5,8, REST,2, REST,2, C5,8, C5,8, REST,8, C5,8, REST,8,
  C5,8, D5,8, REST,8, E5,8, C5,8, REST,8, A4,8, G4,8,
  REST,8, REST,4, E5,8, E5,8, REST,8, E5,8, REST,8, C5,8,
  E5,8, REST,8, G5,8, REST,8, REST,4, G4,8, REST,8, REST,4,
  E5,8, C5,8, REST,8, G4,8, REST,4, GS4,8, REST,8, A4,8,
  F5,8, REST,8, F5,8, A4,8, REST,8, REST,4, B4,8, A5,8,
  REST,8, A5,8, A5,8, G5,8, REST,8, F5,8, E5,8, C5,8,
  REST,8, A4,8, G4,8, REST,8, REST,4, E5,8, C5,8, REST,8,
  G4,8, REST,4, GS4,8, REST,8, A4,8, F5,8, REST,8, F5,8,
  A4,8, REST,8, REST,4, B4,8, F5,8, REST,8, F5,8, F5,8,
  E5,8, REST,8, D5,8, C5,8, REST,8, REST,4, REST,2, C5,8,
  REST,4, G4,8, REST,4, E4,8, REST,8, A4,8, B4,8, A4,8,
  GS4,4, AS4,4, GS4,4, G4,1
};

#endif  // SONGS_CLASSIC_H
