/************************************************************
  songs_user.h - your own tracks
  GENERATED by tools/import_song.py. Regenerate, or edit by hand.

  Holds any number of three-voice tracks. Each one adds a row to
  USER_SONG_ENTRIES, which sketch.ino splices into its playlist.

  To add one:
      python3 tools/import_song.py <file> \
          --voices <lead>,<harmony>,<bass> \
          --bpm <n> --title "<name>" --install

  Installing a title that is already here replaces just that track and
  leaves the others alone.

  Tracks:
    1. 679 (Trap), 180 BPM - 18 bars, 24.0 s x3 = 72.0 s
    2. Let Me Know (R&B), 92 BPM - 14 bars, 36.5 s x2 = 73.0 s
************************************************************/

#ifndef SONGS_USER_H
#define SONGS_USER_H

#include "notes.h"

#define HAVE_USER_SONGS 2

#if HAVE_USER_SONGS


// ---- 1. 679 ----
// lead
const int user0Lead[] = {
  FS5,4, FS5,8, E5,4, D5,8, B4,4, B4,4, D5,8, E5,4,
  FS5,8, D5,4, FS5,4, A5,8, FS5,4, E5,8, D5,4, B4,4,
  B4,8, D5,4, E5,4, REST,8, FS5,4, FS5,8, E5,4, D5,8,
  B4,4, B4,4, D5,8, E5,4, FS5,8, D5,4, FS5,4, A5,8,
  FS5,4, E5,8, D5,4, B4,4, B4,8, D5,4, E5,4, REST,8,
  D5,8, E5,8, D5,8, E5,8, D5,8, E5,8, D5,8, E5,8,
  D5,8, E5,8, D5,8, E5,8, D5,8, E5,8, D5,8, E5,8,
  FS5,2, FS5,4, REST,4, FS5,2, E5,8, D5,8, B4,4, FS5,4,
  FS5,8, E5,4, D5,8, B4,4, B4,4, D5,8, E5,4, FS5,8,
  D5,4, FS5,4, A5,8, FS5,4, E5,8, D5,4, B4,4, B4,8,
  D5,4, E5,4, REST,8, FS5,1, B4,1
};
// harmony
const int user0Harm[] = {
  G4,8, B4,8, D5,8, B4,8, G4,8, B4,8, D5,8, B4,8,
  A4,8, CS5,8, E5,8, CS5,8, A4,8, CS5,8, E5,8, CS5,8,
  B4,8, D5,8, FS5,8, D5,8, B4,8, D5,8, FS5,8, D5,8,
  B4,8, D5,8, FS5,8, D5,8, B4,8, D5,8, FS5,8, D5,8,
  G4,8, B4,8, D5,8, B4,8, G4,8, B4,8, D5,8, B4,8,
  A4,8, CS5,8, E5,8, CS5,8, A4,8, CS5,8, E5,8, CS5,8,
  B4,8, D5,8, FS5,8, D5,8, B4,8, D5,8, FS5,8, D5,8,
  B4,8, D5,8, FS5,8, D5,8, B4,8, D5,8, FS5,8, D5,8,
  G4,4, REST,4, G4,4, REST,4, A4,4, REST,4, A4,4, REST,4,
  B4,4, REST,4, B4,4, REST,4, B4,4, REST,4, B4,4, REST,4,
  G4,8, B4,8, D5,8, B4,8, G4,8, B4,8, D5,8, B4,8,
  A4,8, CS5,8, E5,8, CS5,8, A4,8, CS5,8, E5,8, CS5,8,
  B4,8, D5,8, FS5,8, D5,8, B4,8, D5,8, FS5,8, D5,8,
  B4,8, D5,8, FS5,8, D5,8, B4,8, D5,8, FS5,8, D5,8,
  D5,1, D5,1
};
// bass
const int user0Bass[] = {
  G4,1, A4,1, B4,1, B4,1, G4,1, A4,1, B4,1, B4,1,
  G4,1, A4,1, B4,1, B4,1, G4,1, A4,1, B4,1, B4,1,
  G4,1, B4,1
};

// ---- 2. Let Me Know ----
// lead
const int user1Lead[] = {
  CS5,4, CS5,8, B4,8, A4,4, FS4,4, A4,4, B4,8, CS5,4,
  REST,8, E5,4, CS5,4, CS5,8, B4,8, A4,4, FS4,4, A4,4,
  B4,8, A4,4, REST,8, REST,4, CS5,4, CS5,8, B4,8, A4,4,
  FS4,4, A4,4, B4,8, CS5,4, REST,8, E5,4, FS5,4, E5,8,
  CS5,8, B4,4, A4,4, B4,2, REST,2, FS4,8, FS4,8, REST,8,
  A4,8, A4,4, REST,4, B4,8, B4,8, REST,8, CS5,8, CS5,4,
  REST,4, D5,8, D5,8, REST,8, CS5,8, B4,4, A4,4, FS4,2,
  REST,2, CS5,1, FS4,1
};
// harmony
const int user1Harm[] = {
  FS4,8, A4,8, CS5,8, A4,8, FS4,8, A4,8, CS5,8, A4,8,
  D5,8, FS5,8, A5,8, FS5,8, D5,8, FS5,8, A5,8, FS5,8,
  A4,8, CS5,8, E5,8, CS5,8, A4,8, CS5,8, E5,8, CS5,8,
  E4,8, GS4,8, B4,8, GS4,8, E4,8, GS4,8, B4,8, GS4,8,
  FS4,8, A4,8, CS5,8, A4,8, FS4,8, A4,8, CS5,8, A4,8,
  D5,8, FS5,8, A5,8, FS5,8, D5,8, FS5,8, A5,8, FS5,8,
  A4,8, CS5,8, E5,8, CS5,8, A4,8, CS5,8, E5,8, CS5,8,
  E4,8, GS4,8, B4,8, GS4,8, E4,8, GS4,8, B4,8, GS4,8,
  FS4,4, REST,4, FS4,4, REST,4, D5,4, REST,4, D5,4, REST,4,
  A4,4, REST,4, A4,4, REST,4, E4,4, REST,4, E4,4, REST,4,
  A4,1, FS4,1
};
// bass
const int user1Bass[] = {
  FS3,1, D3,1, A3,1, E3,1, FS3,1, D3,1, A3,1, E3,1,
  FS3,1, D3,1, A3,1, E3,1, FS3,1, FS3,1
};

// Spliced into PLAYLIST by sketch.ino. The trailing comma
// on the last row is deliberate.
#define USER_SONG_ENTRIES \
  { "679", "Trap", 180, { SCORE(user0Lead), SCORE(user0Harm), SCORE(user0Bass) } }, \
  { "Let Me Know", "R&B", 92, { SCORE(user1Lead), SCORE(user1Harm), SCORE(user1Bass) } },

#endif  // HAVE_USER_SONGS

#endif  // SONGS_USER_H
